### ISSUE TITLE
Issue with sidebar in small screens 

### ISSUE THREAD

**Issue by lunayach** [systers/PC-Prep-Kit#102]
## Description
As a user,
I need to sometimes access the application on the small screen as well,
 so that I can enjoy cross-platform functionality.
## Mocks
After '/login' screen, I am redirected to '/menu' screen. In 'Navbar.component.ts', the initial state for navbar has been set to be 'out'. I think for small screen devices, this should be made 'in'.
![rsz_respnsiveness](https://user-images.githubusercontent.com/21227893/37254298-faea6526-2561-11e8-872f-fbb8853c086d.png)

### Update [Required]
- [ ] Calling the toggle() method when say, (window.screen.width<512) returning true would animate that thing to state 'in'.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by Raxerz** [comment]
Great. Go ahead and make the PR. This issue can be closed I suppose.

**Comment by Buddhiprabha** [comment]
Duplicate.
