### ISSUE TITLE
Prevention Activity - I Stop the breeding UI

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#121]
## Description
As a user,
I need see the UI for Stop the breeding activity,
so that I can play the game when the backend is ready.

### Update [Required]
- [ ] UI fully functioning
- [ ] Unit Testing coverage > 80% 
- [ ] Pass Travis Build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
25-30 hours

**Comment by Raxerz** [comment]
At @shreyans29  this is a duplicate of #120 . Can you please check?

**Comment by shreyans29** [comment]
@Raxerz  yes ,right sorry.
