### ISSUE TITLE
Prevention Activity - I Stop the breeding Back end

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#122]
## Description
As a developer,
I need build the backend for Stop the breeding activity,
so that the user can play the game.

### Update [Required]
- [ ] Fully functioning Backend
- [ ] UI - Backend Integrated
- [ ] Sanity Test 
- [ ] Unit Testing coverage > 80% 
- [ ] pass travis build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
5-6 hours

**Comment by Raxerz** [comment]
@shreyans29 This has also been covered as a part of #120 . Can you please confirm?

**Comment by paavininanda** [comment]
@Raxerz I also think so. I think this issue can be closed. @shreyans29?

**Comment by Buddhiprabha** [comment]
Duplicated.
