### ISSUE TITLE
PC Prep Kit branding guidelines updation

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#124]
## Description
As a user,
I need the branding guidelines updated,
so that I can have a better feel of the application.

### Update [Required]
- [ ] Updating Old logos with new ones.
- [ ] Updating colors.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
5-6 hours

**Comment by shreyans29** [comment]
@paavininanda @Raxerz Do you think there are any more tasks which needs to be done apart from the 2 mentioned here ?  5-6 hrs seems a lot for replacing logos and updating colors.

**Comment by paavininanda** [comment]
@shreyans29 Yea I also think that its a lot of time, and I also don't remember any other branding upgradation that might be needed.
