### ISSUE TITLE
Enhancements to do's and don'ts game

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#156]
## Description
As a [USER],
I need to modify do's and don'ts game,
so that I can play it with more difficulty levels too.

### Update [Required]
- [ ] Add separate lists of questions for different levels.
- [ ] Allow the user to press the submit button to submit.
- [ ] Creating a reset button so that its easy to reset all the available options. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
4-5 hours

**Comment by Buddhiprabha** [comment]
@paavininanda are you adding the "reset" button as a separate issue? It can be added to this.

**Comment by paavininanda** [comment]
Oh, I missed that, will add it here itself.
