### ISSUE TITLE
Maintain Malaria Chatbot Corpus

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#159]
## Description
As a developer,
I need to maintain a file with intents and corresponding sentences,
so that I can contributors can add sentences to the file, which can be used to train the chatbot.

### Update [Required]
- [ ] New file in the repository with Intents and sentences.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 hours

**Comment by lunayach** [comment]
@Buddhiprabha as a PR, do I need to send the google document that we made for collecting responses here.

**Comment by Buddhiprabha** [comment]
@lunayach you need to add it as a document to the repo. Download and properly format the document before adding.
