### ISSUE TITLE
Malaria Web app - Proposed UI

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/PC-Prep-Kit#3]
[Malaria Web App.pdf](https://github.com/systers/PC-Prep-Kit/files/187883/Malaria.Web.App.pdf)

This is the malaria Web app UI mockup based on Material Design.

**Comment by tsah20** [comment]
Hey is this project reserved for GSOC candidates?

**Comment by MeepyMay** [comment]
@tsah20: Hello Tanya! We will propose this project to GSoC, but it's not reserved for it.

Please join Systers OpenSource slack and add #malaria-web channel. We just started discussing our plans for creating this app. systers.io/slack-systers-opensource/

**Comment by Afrin14** [comment]
@MeepyMay  I too would like to be a part of the discussion and contribute to this project. But I couldn't find       #malaria-web channel in the said above site. I am already a member in Systers Open Source slack group.

**Comment by Rupinderwadali** [comment]
@Afrin14 The channel name is #pc-prep-kit for malaria web.

**Comment by Afrin14** [comment]
@Rupinderwadali thank you.
