### ISSUE TITLE
User enters a valid email.

### ISSUE THREAD

**Issue by MeepyMay** [systers/PC-Prep-Kit#51]
## Description
As a developer,
I want to check if the user enters a working email,
so that I can send verification emails with no bounces.

## Mocks
![screen shot 2017-08-24 at 1 53 18 pm](https://user-images.githubusercontent.com/2440938/29680789-ab729a0c-88d3-11e7-9029-7f407264def1.png)

## Acceptance Criteria
- No fake emails are able to be entered in the "Sign Up" screen.
- Error message shows once user presses "Sign Up."

## Definition of Done
- Created a PR and referenced this Issue.
- Approved by Buddhi

## Estimation
2 hours

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PC-Prep-Kit/pull/57
