### ISSUE TITLE
User gets visible feedback on "Do's" and Don't's"

### ISSUE THREAD

**Issue by MeepyMay** [systers/PC-Prep-Kit#52]
## Description
As a user,
I want to receive visual feedback,
so that I can know I am choosing the wrong list.

## Mocks
![screen shot 2017-08-24 at 2 10 15 pm](https://user-images.githubusercontent.com/2440938/29681548-fec88156-88d5-11e7-98d9-d67c3bad4075.png)

## Acceptance Criteria
- Entire "Do" or "Don't" box's line is switched from black to RED.
- Uses PC Branding Guidelines (Red: #B71234)

## Definition of Done
- Created a PR and referenced this Issue.
- Approved by Buddhi

## Estimation
1 hour

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PC-Prep-Kit/pull/55
