### ISSUE TITLE
User needs a better transition in "Medication & Labels" 

### ISSUE THREAD

**Issue by MeepyMay** [systers/PC-Prep-Kit#53]
## Description
As a user,
I want to see clear transitions from one game to the next,
so that I can clearly complete the game's goals.

## Mocks
![screen shot 2017-08-24 at 2 14 10 pm](https://user-images.githubusercontent.com/2440938/29681768-c2244658-88d6-11e7-9790-2ad0b1bbe010.png)

## Acceptance Criteria
- Keep the correct answers present after user completes "right side-effects"
1. While on this screen, "Reset" button should change to "Next" to prompt the "right description" game.
- Change text color "right description" and "right side-effects" to Orange #DC5034

## Definition of Done
- Created a PR and referenced this Issue.
- Approved by Buddhi

## Estimation
2 hours

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PC-Prep-Kit/pull/56
