### ISSUE TITLE
Merge Fixes

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#61]
There are many places in the application which have minor bugs due to merging incorrectly. 

To be fixed: 
- Remove verificationCode Column 
- Changing bcrypt version to 1.0.2 (1.0.3 gives some problem)
- Adding library to registration.js 
- color changes for branding 
- removing duplicate string from english.json 

All the issues are caused due to merging incorrectly.

**Comment by Buddhiprabha** [comment]
@shreyans29 Can you please elaborate on what the minor bugs are?

**Comment by shreyans29** [comment]
@Buddhiprabha I added the list of things to be fixed.

**Comment by Buddhiprabha** [comment]
@shreyans29 what are the problems in bcrypt version to 1.0.3?

**Comment by shreyans29** [comment]
@Buddhiprabha It has this issue which was causing problems with its installations.
https://github.com/kelektiv/node.bcrypt.js/issues/537

In the comments the solution mentioned was to use 1.0.2 for a while till they fix this issue by uploading some dependencies (currently missing).

**Comment by Buddhiprabha** [comment]
Fixed
