### ISSUE TITLE
email-verify npm package not present in package.json

### ISSUE THREAD

**Issue by arvindkalra** [systers/PC-Prep-Kit#65]
![email-verify](https://user-images.githubusercontent.com/29686907/32278176-d77f0bec-bf3a-11e7-8afa-0c87a9e0ca5a.png)
This error shows up when the npm start command is run as the email-verify package is not present in the package.json file so it is not installed on npm install

Allow me to fix this bug.

**Comment by arvindkalra** [comment]
Please Assign me to solve this issue.

**Comment by Buddhiprabha** [comment]
Please follow the issue submission template.
