### ISSUE TITLE
Error in building the app

### ISSUE THREAD

**Issue by ankita132** [systers/PC-Prep-Kit#70]
**Description**
MaterialModule was depreciated in version 2.0.0-beta.3 and it has been removed completely in version 2.0.0-beta.11.We need to include individual material component modules in order to use them in the app.

**Mock**
![image](https://user-images.githubusercontent.com/22315151/36273299-143ceea6-12aa-11e8-971d-b6def1ba434b.png)

**Acceptance Criteria**
- The material module needs to be removed from the files where modules are imported
- 'md' tags in the files have to removed and changed to 'mat'

**Definition of done**
Sending a PR and getting it reviewed by the mentor

**Estimation** 
1 to 2 hour

**Comment by shreyans29** [comment]
@ankita132 You can go ahead and work on this. Try Updating the material-module to the latest version. The Estimation I feel is quite wrong. It is a 3+ hrs task depending on how many things you have to change.

**Comment by shreyans29** [comment]
The same issues is being addressed in issue #97 . This issue can be closed.

**Comment by ankita132** [comment]
Quite possible.It really needs to be looked upon.I will just edit the issue

**Comment by ankita132** [comment]
Okay
