### ISSUE TITLE
Don'ts display empty boxes

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#73]
**Description**
>As a user, while playing the drag and drop game, when anything is dropped into don'ts, the text of the data automatically disappears,
>I would never want the text to disappear so that I can see what I just dropped.
>so that I can view the page easily.

**Acceptance Criteria**
Text begin displayed.

**Definition of Done**
Sending a PR and getting it reviewed by mentor(s) .

**Mocks**
This is what should not happen.
![screen shot 2018-02-16 at 3 29 04 pm](https://user-images.githubusercontent.com/24737071/36311011-dc59a618-134f-11e8-84dd-8ccd901b31a8.png)

**Estimation**
1-2 days

**Comment by ankita132** [comment]
working on this issue.

**Comment by shreyans29** [comment]
@paavininanda @ankita132  This was an issue due to version mismatch and Angular Material not working. This should be working fine.

**Comment by Buddhiprabha** [comment]
@paavininanda @shreyans29 can you please confirm if this issue is still valid? Please close otherwise.

**Comment by paavininanda** [comment]
This issue has been resolved by #92
