### ISSUE TITLE
Side menu cannot be closed.

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#74]
**Description**
>As a user, when on the url `http://localhost:3000/menu`, the side menu cannot be closed anymore.
>I might want to close it when not of any use,
>so that its easy for me to view the full page.

**Acceptance Criteria**
The button working all the time.

**Definition of Done**
Sending a PR and getting it reviewed by mentor(s) .

**Mocks**
Currently there is no button at all.
![screen shot 2018-03-19 at 12 28 27 am](https://user-images.githubusercontent.com/24737071/37569728-84013cb8-2b0c-11e8-9d6b-5357e9164a15.png)

A button of this kind would work.
![screen shot 2018-02-17 at 1 20 49 pm](https://user-images.githubusercontent.com/24737071/36339192-c6e1043e-13e5-11e8-9097-8b1dfb3124ff.png)

**Estimation**
4-5 hours

**Comment by paavininanda** [comment]
After #92 got merged, this button which could be used to close the sidebar has disappeared all together.

**Comment by lunayach** [comment]
I'm not facing this issue in chrome Ubuntu, after the merged PR.
