### ISSUE TITLE
No logout button

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#75]
**Description**
>As a user, I might want to log out of the application and log in using some other account,
>I would want a button for that purpose,
>so that its easy for me to logout.

**Acceptance Criteria**
A working logout button working.

**Definition of Done**
Sending a PR and getting it reviewed by mentor(s) .

**Estimation**
2-3 days

**Comment by shreyateeza** [comment]
@paavininanda I would like to work on this issue! Please assign it to me. :smile:

**Comment by paavininanda** [comment]
Hi @shreyateeza! You can work on this issue since its not assigned to anyone currently.

**Comment by shreyateeza** [comment]
There are some problems coming while running the files locally in my machine. So, this issue is up for grabs. As I am not working on it currently. :slightly_smiling_face:

**Comment by lunayach** [comment]
It is there after the latest PR. (Chrome, Ubuntu)

**Comment by paavininanda** [comment]
It is already working after the latest PR.
