### ISSUE TITLE
Disoriented title 

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#78]
**Description**
>As a user, when on the url `http://localhost:3000/menu`, in fullscreen mode, the title main menu appears disoriented.
>I would never want the page to look disoriented,
>so that it looks proper.

**Acceptance Criteria**
Main menu in one single line.

**Definition of Done**
Sending a PR and getting it reviewed by mentor(s) .

**Mocks**
Main menu should be displayed in one single line instead.
![screen shot 2018-02-19 at 12 09 22 am](https://user-images.githubusercontent.com/24737071/36355449-5256b6e8-1509-11e8-8bd8-75d355274b03.png)

**Estimation**
2-3 hours

**Comment by ankita132** [comment]
Can I work on this issue ?

**Comment by paavininanda** [comment]
@ankita132 Yes, since this issue has not been taken up by anyone, you can go ahead. 👍

**Comment by lunayach** [comment]
This issue is not there after the latest PR.

**Comment by paavininanda** [comment]
This issue doesn't exist anymore.
