### ISSUE TITLE
Replacing the Peace Corps logo with the new redesigned logo

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#79]
**Description**
>As a user, abiding the Peace Corps branding guidelines is important.
>I would want the new logo to be displayed instead,
>so that the guidelines are being followed.

**Acceptance Criteria**
We currently have various new logos, which will be used depending upon the screen size. Hence a responsive design for the page needs to be implemented. New logos should be displayed instead of the old one.

**Definition of Done**
Sending a PR and getting it reviewed by mentor(s) .

**Mocks**
Adding the new logo here.

![screen shot 2018-02-19 at 12 18 16 am](https://user-images.githubusercontent.com/24737071/36355556-ff3b7c76-150a-11e8-955d-9729fc98e817.png)

These are the new logos
![screen shot 2018-02-25 at 7 27 51 pm](https://user-images.githubusercontent.com/24737071/36642203-0017911e-1a62-11e8-930e-e0328458aed7.png)

**Estimation**
5-6 hours

**Comment by zyang7** [comment]
Hello, if nobody is working on this, I would like to take it on.

**Comment by paavininanda** [comment]
Will be covered in https://github.com/systers/PC-Prep-Kit/issues/124
