### ISSUE TITLE
Missing title element in head element!

### ISSUE THREAD

**Issue by shreyateeza** [systers/PC-Prep-Kit#82]
## Description
There is no title element found in the head element of index.html. Add suitable title to be shown on the tab.

## Definition of Done
- [ ] Approval from 1 mentor.

## Estimation
Less than 5 minutes.

## Difficulty
First-timers-only

**Comment by paavininanda** [comment]
@shreyateeza I am not sure which index.html are you talking about? Because [this](https://github.com/systers/PC-Prep-Kit/blob/develop/src/index.html) already has a title element.

**Comment by shreyateeza** [comment]
My bad. Was looking at the index.html of master branch. 🙈 
@paavininanda Is this issue still valid? Or it needs to be closed?

**Comment by paavininanda** [comment]
@shreyateeza It would be better to close the issue 👍
