### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by shreyateeza** [systers/PC-Prep-Kit#83]
## Description
Add a template describing the format of writing an issue.
As a user,
I need to add the Issue Template,
so that this template will be followed to write the issues.

## Mocks
-- Not Applicable -

### Update [Required]
- [ ] Create ISSUE_TEMPLATE.md
 
## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
Less than 60 minutes

**Comment by Buddhiprabha** [comment]
Acceptance Criteria is missing. Can you please add it?

**Comment by shreyateeza** [comment]
@Buddhiprabha I have updated it. You can reopen it.
P.S.: This repo is yet to have an issue template. :stuck_out_tongue: 
Thank you!

**Comment by Buddhiprabha** [comment]
All repos follow Systers' template.

**Comment by Buddhiprabha** [comment]
This has been added to the repo from a PR sent previously.
