### ISSUE TITLE
Password should not be stored directly into the database

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#85]
**Description**
>As a user,
>I would never want my password to be stored in the database directly.
>so that nobody gets to know about my personal information.

**Acceptance Criteria**
Login working correctly and password being stored after encryption.
- We must encrypt the password and then store it in the database. 
- To implement the login authentication, we will have to again pass the password to the encrypt function and match it with the stored hash.
- Packages like bcrypt can be used to make the above changes.

**Definition of Done**
Sending a PR along with a screenshot of the table user_accounts and getting it reviewed by mentor(s)

**Estimation**
2-3 hours

**Comment by AnkitKhatri55555** [comment]
@paavininanda ,can i work on this?

**Comment by paavininanda** [comment]
@AnkitKhatri55555 You can surely work on this issue since no one is working. But please make sure that you send a PR to your own forked repo, until this issue gets approved. Moreover I'd suggest you to work on only one issue at a time. :)

**Comment by AnkitKhatri55555** [comment]
Sure , @paavininanda

**Comment by paavininanda** [comment]
This does not need to be addressed anymore. It is working fine after #92 got merged.
