### ISSUE TITLE
.travis.yml file missing 

### ISSUE THREAD

**Issue by shreyans29** [systers/PC-Prep-Kit#91]
**Description:** As a Contributor, I should be able to send pull requests which are verified by travis to accomplish Continuous Integration.

**Acceptance Criteria :**  New PRs should successfully pass travis tests.
**Update :** 
Add travis.yml file to the repo.
Configure the travis.yml file to run proper node versions, set up database and run API tests. 

**Definition of Done :** 
Send a PR which satisfies acceptance criteria. 
Approved by the repo Maintainer.

**Estimate** : 4 hrs

**Comment by MeepyMay** [comment]
This does not follow the issue template. Please update.

**Comment by MeepyMay** [comment]
Nevermind! I just noticed we forgot to add here. @Janiceilene ~

**Comment by Janiceilene** [comment]
@MeepyMay Issue Template is merged, but the PRs for the PR template and a few others are waiting to be merged.

**Comment by Buddhiprabha** [comment]
This does not follow the issue template. Please make the changes.

**Comment by shreyans29** [comment]
- @Buddhiprabha Added missing Sections

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PC-Prep-Kit/pull/92
