### ISSUE TITLE
URL points to wrong activity and inability to navigate back using the back helper button

### ISSUE THREAD

**Issue by Raxerz** [systers/PC-Prep-Kit#93]
## Description
As a user,
I should be able to see that the url points to the current activity and I should also be able to navigate to the previous activity from the third activity (Doctor chat) of Medication and Labels stage, by clicking on the back navigation arrow provided at the bottom,
so that I can navigate easily between activities.

## Mocks
![screenshot from 2018-03-02 15 43 43](https://user-images.githubusercontent.com/16686007/36894202-9bc17a4a-1e30-11e8-89db-e2c1acb4c217.png)

### Error log screenshot:
URL points to activity-2 instead of activity-3
![screenshot from 2018-03-02 15 50 28](https://user-images.githubusercontent.com/16686007/36894492-88c7374e-1e31-11e8-89ae-7daa7b995f99.png)

### Update [Required]
- [ ] URL should point to the correct activity.
- [ ] User should be able to navigate to the previous activity from this activity using the helper buttons

## Definition of Done
- [ ] The item listed as part of Acceptance Criteria should be complete.
- [ ] Approval by any of the admins, maintainers or mentors.

## Estimation
1-2 hours

**Comment by akshitac8** [comment]
Hello, Is this bug up for solving?

**Comment by Raxerz** [comment]
Yes it is.

**Comment by akshitac8** [comment]
Hey,
Can I know the files to be edited?
Thank you:)

**Comment by Raxerz** [comment]
@akshitac8 Try to understand the codebase and see if you can find the files fix. It will be interesting and challenging if you can find these files and make the fix rather than me or anyone else leading you to the files. If you need any help in understanding the code flow, please feel free to ping the #pcprepkit channel on slack.

**Comment by lunayach** [comment]
This issue is not there after the merged PR.

**Comment by Raxerz** [comment]
Closing this issue since it has been resolved in one of the recent PRs.
