### ISSUE TITLE
Replace the use of Material Module in Angular

### ISSUE THREAD

**Issue by ankita132** [systers/PC-Prep-Kit#97]
## Description
As a user,
I need to replace the package Material Module which is deprecated in the newer version of angular-cli.

## Mocks
![image](https://user-images.githubusercontent.com/22315151/37118457-50ac40b4-227a-11e8-9755-4a81f3f2e89d.png)

## Acceptance Criteria
Replace the use of material-module.

### Update [Required]
- [ ] update the prefix in your template for example, md-button should now be mat-button

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 to 5 hours

**Comment by shreyans29** [comment]
@ankita132 You can go ahead and work on it. Update to the latest version of Angular Material.

**Comment by paavininanda** [comment]
Will be covered in https://github.com/systers/PC-Prep-Kit/issues/118
